language: node_js
node_js:
  - '10'
cache: yarn

install: 
  - yarn install
script:
  - yarn run clean && gatsby build --prefix-paths
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  target_branch: master

branches:
  only:
    - develop